use crate::*;

pub mod cmd_attach_session;
pub mod cmd_bind_key;
pub mod cmd_break_pane;
pub mod cmd_capture_pane;
pub mod cmd_choose_tree;
pub mod cmd_command_prompt;
pub mod cmd_confirm_before;
pub mod cmd_copy_mode;
pub mod cmd_detach_client;
pub mod cmd_display_menu;
pub mod cmd_display_message;
pub mod cmd_display_panes;
pub mod cmd_find;
pub mod cmd_find_window;
pub mod cmd_if_shell;
pub mod cmd_join_pane;
pub mod cmd_kill_pane;
pub mod cmd_kill_server;
pub mod cmd_kill_session;
pub mod cmd_kill_window;
pub mod cmd_list_buffers;
pub mod cmd_list_clients;
pub mod cmd_list_keys;
pub mod cmd_list_panes;
pub mod cmd_list_sessions;
pub mod cmd_list_windows;
pub mod cmd_load_buffer;
pub mod cmd_lock_server;
pub mod cmd_move_window;
pub mod cmd_new_session;
pub mod cmd_new_window;
pub mod cmd_parse;
pub mod cmd_paste_buffer;
pub mod cmd_pipe_pane;
pub mod cmd_queue;
pub mod cmd_refresh_client;
pub mod cmd_rename_session;
pub mod cmd_rename_window;
pub mod cmd_resize_pane;
pub mod cmd_resize_window;
pub mod cmd_respawn_pane;
pub mod cmd_respawn_window;
pub mod cmd_rotate_window;
pub mod cmd_run_shell;
pub mod cmd_save_buffer;
pub mod cmd_select_layout;
pub mod cmd_select_pane;
pub mod cmd_select_window;
pub mod cmd_send_keys;
pub mod cmd_server_access;
pub mod cmd_set_buffer;
pub mod cmd_set_environment;
pub mod cmd_set_option;
pub mod cmd_show_environment;
pub mod cmd_show_messages;
pub mod cmd_show_options;
pub mod cmd_show_prompt_history;
pub mod cmd_source_file;
pub mod cmd_split_window;
pub mod cmd_swap_pane;
pub mod cmd_swap_window;
pub mod cmd_switch_client;
pub mod cmd_unbind_key;
pub mod cmd_wait_for;

unsafe extern "C" {
    pub static mut cmd_table: [*const cmd_entry; 0usize];
    pub fn cmd_log_argv(_: c_int, _: *mut *mut c_char, _: *const c_char, ...);
    pub fn cmd_prepend_argv(_: *mut c_int, _: *mut *mut *mut c_char, _: *const c_char);
    pub fn cmd_append_argv(_: *mut c_int, _: *mut *mut *mut c_char, _: *const c_char);
    pub fn cmd_pack_argv(_: c_int, _: *mut *mut c_char, _: *mut c_char, _: usize) -> c_int;
    pub fn cmd_unpack_argv(_: *mut c_char, _: usize, _: c_int, _: *mut *mut *mut c_char) -> c_int;
    pub fn cmd_copy_argv(_: c_int, _: *mut *mut c_char) -> *mut *mut c_char;
    pub fn cmd_free_argv(_: c_int, _: *mut *mut c_char);
    pub fn cmd_stringify_argv(_: c_int, _: *mut *mut c_char) -> *mut c_char;
    pub fn cmd_get_alias(_: *const c_char) -> *mut c_char;
    pub fn cmd_get_entry(_: *mut cmd) -> *const cmd_entry;
    pub fn cmd_get_args(_: *mut cmd) -> *mut args;
    pub fn cmd_get_group(_: *mut cmd) -> c_uint;
    pub fn cmd_get_source(_: *mut cmd, _: *mut *const c_char, _: *mut c_uint);
    pub fn cmd_parse(_: *mut args_value, _: c_uint, _: *const c_char, _: c_uint, _: *mut *mut c_char) -> *mut cmd;
    pub fn cmd_copy(_: *mut cmd, _: c_int, _: *mut *mut c_char) -> *mut cmd;
    pub fn cmd_free(_: *mut cmd);
    pub fn cmd_print(_: *mut cmd) -> *mut c_char;
    pub fn cmd_list_new() -> *mut cmd_list;
    pub fn cmd_list_copy(_: *mut cmd_list, _: c_int, _: *mut *mut c_char) -> *mut cmd_list;
    pub fn cmd_list_append(_: *mut cmd_list, _: *mut cmd);
    pub fn cmd_list_append_all(_: *mut cmd_list, _: *mut cmd_list);
    pub fn cmd_list_move(_: *mut cmd_list, _: *mut cmd_list);
    pub fn cmd_list_free(_: *mut cmd_list);
    pub fn cmd_list_print(_: *mut cmd_list, _: c_int) -> *mut c_char;
    pub fn cmd_list_first(_: *mut cmd_list) -> *mut cmd;
    pub fn cmd_list_next(_: *mut cmd) -> *mut cmd;
    pub fn cmd_list_all_have(_: *mut cmd_list, _: c_int) -> c_int;
    pub fn cmd_list_any_have(_: *mut cmd_list, _: c_int) -> c_int;
    pub fn cmd_mouse_at(_: *mut window_pane, _: *mut mouse_event, _: *mut c_uint, _: *mut c_uint, _: c_int) -> c_int;
    pub fn cmd_mouse_window(_: *mut mouse_event, _: *mut *mut session) -> *mut winlink;
    pub fn cmd_mouse_pane(_: *mut mouse_event, _: *mut *mut session, _: *mut *mut winlink) -> *mut window_pane;
    pub fn cmd_template_replace(_: *const c_char, _: *const c_char, _: c_int) -> *mut c_char;
}
